library(ggnetwork)
install.packages("devtools")
library(devtools)
install_github("DougLuke/UserNetR")
library(UserNetR)
data(Bali)

Network <- ggnetwork(Bali,layout="kamadakawai")
(ggplot(Bali, aes(x,y, xend=xend, yend=yend))
  + ggtitle('Bali Terrorist Network, Role as Nodes')
  + geom_edges(color="lightgrey") 
  + geom_nodes(alpha=0.6,size=5) 
  + geom_nodetext(aes(label=role),color="red") 
  + theme_blank())